// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxqfwhfyiuxyykzotxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cWZ3aGZ5aXV4eXlrem90eGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDAzNzgsImV4cCI6MjA3MTg3NjM3OH0.ZT5gNrmJDDTON98F4b1ZuMTiz4AKSg3OSVBDONck44U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});